<?php $menu="faqs";include("header.php"); ?>
	<div class="faqs"><br><br>
		<div class="slider-faqs">
			<div class="slider-wrapper theme-default">
				<div class="ribbon"></div>
				<div id="slider" class="nivoSlider">
					<img src="/images/Honest-Fireplace-Main1.jpg" alt="" />
					<img src="/images/Honest-Fireplace-Main2.jpg" alt="" />
				</div>
			</div>
		</div>
		<div class="text-left">
			<img src="images/lcdoverfireplace.jpg" alt="TV above fireplace" align="right"/><br><br>
			<img src="images/q1.jpg" alt="What is the process for getting a TV installed above my fireplace" /><br>
			All we need is some basic details such as: TV size, the type of wall material, list of equipment and whether or not you'd like the wiring to be concealed, from there we establish ballpark cost. We then may schedule an on-site consultation for further inspectionor in most instances we can schedule your installation right away.  <br><br>
			<img src="images/q2.jpg" alt="Is it expensive to hang a TV above the fireplace" /><br>
			Fireplace TV install, like anything else, can range from basic to advanced.Our basic service for TV's 37-60" starts at $199 and may go upbased on the addition of optional services. A typical fireplace TV installincluding electrical, wire concealment and cabling is around $550-650.* 
		</div>
		<br style="clear:both"><br>
		<div class="text-right">
			<img src="images/tvfire.jpg" align="left"/><br><br><br><br>
			<img src="images/q3.jpg" alt="Can I still use/turn on my fireplace" /><br>
			YES, all Honest customers can still turn on, or use their fireplaces just as they did before.<br><br>
			<img src="images/q4.jpg" alt="Will the heat generated by my fireplace hurt the TV" /><br>
			NO, the exhaust gases are contained within the flue or exhaust pipe which is separated a  good distance from the facia or front wall of the  fireplace. By the time the gases reach the height of the TV they have already cooled and do not pose a heat threat.
		</div>
		<br style="clear:both"><br>
		<div class="text-left">
			<img src="images/tvfire3.jpg" align="right"/><br><br>
			<img src="images/q5.jpg" alt="Will mounting a TV above my fireplace hurt or damage the fireplace itself" /><br>
			NO, Honest employs minimally invasive methods when mounting your TV to the wall-surface and our expert technicians never compromise  the inner structure of your fireplace.<br><br>
			<img src="images/q6.jpg" alt="Does it matter what kind of fireplace I have or how old my home is" /><br>
			Honest has installed TVs in homes with fireplaces built in the early 1900s, as well as new homes. Although some homes might present a greater challenge over others we have conquered hundreds of fireplaces. With a lot of ingenuity and some elbow grease, we make it happen.
		</div>
		<br style="clear:both"><br>
		<div class="text-right">
			<img src="images/tvfire4.jpg" align="left"/><br><br>
			<img src="images/q7.jpg" alt="I want a clean look, can you conceal the wiring and power cord for a Fireplace TV" /><br>
			YES, the majority of Honest customers choose to have the  wiring concealed and have us install an electricial outlet to power the TV and meet code. Honest has trained expert technicians that can handle both the A/V wiring as well as the electrical-work for your fireplace install. No need to call separate contractors.<br><br>
			<img src="images/q8.jpg" alt="Can you conceal wiring for a fireplace TV even if there is no attic or crawl space above the room" /><br>
			YES, Honest Install employs many methods and techniques to tackle in-wall wire concealment when it comes to fireplace TVs. Even homes without accessible crawl space above the room can have a clean look without any visible wiring or cords.
			<br style="clear:both"><br>
		</div>
		<div class="text-left">
			<img src="images/tvfire5.jpg" align="right"/><br><br>
			<img src="images/q9.jpg" alt="If my fireplace is made of stone, brick or tile, is that a problem" /><br>
			NO, Honest installs TVs on all types of wall surfaces: irregular stone, uniform brick, marble, granite, ceramic tile, cement, cinder block, drywall, sheetrock, etc.   <br><br>
			<img src="images/q10.jpg" alt="How will this affect the re-sale value of my home" /><br>
			In most rooms the focal point is the fireplace and so this is the primary reason for most customers to mount the TV above the fireplace in the first place. It is only natural to assume that the next owners may have the option to do the same,  only now you may advertise the home as "prewired" for a fireplace TV and easily add the cost of the installation to the asking price.  
		</div><br><br><br><br>
		<img class="fullscreen" src="http://www.honestinstall.com/images/divbar.jpg" /><br><br><br>
		<span style="font-family:arial">*Prices are based on averages, Fireplace TV installs vary from home to home and can be higher based on necessary or optional services, call for pricing. </span><br>
	</div>
	<div class="mainBG"><BR><BR>
		<div class="formbox">
			<h4>Schedule It or Ask a Question</h4>
			<?php $webpage="Fireplace FAQs Inquiry"; include("includes/jf-serviceform.php"); ?> 
		</div><br><br><br>
		<p class="bottomText" align="center">
			<!--Start Customer Lobby-->
			<a onClick="window.open('http://www.customerlobby.com/reviews/403/honest-install/' ,'ReviewPage', 'statusbar=no,menubar=no,toolbar=no,scrollbars=yes,resizable=yes,width=540, height=575,left=570,top=200,screenX=570,screenY=200'); return false;" href="http://www.customerlobby.com/reviews/403/honest-install/" target="_blank">
				<img style="display: none" border=0 alt="Statistics" src="http://www.customerlobby.com/ctrack-403">
				<img border="0" alt="Review of Honest Install" src="http://www.customerlobby.com/img/403/standard/">
			</a><!--End Customer Lobby--> 
			<br><br>SCHEDULE SERVICE NOW!<strong>&nbsp; 972-470-3528<br><br>
			</strong>E-Mail us Directly: <a title="E-Mail Honest Install" href="mailto:info@HonestInstall.com"><strong>info@HonestInstall.com</strong></a>
		</p>
		<p class="bottomText" align="center"><a href="contact.php"><strong>Schedule Service/Inquiry Form</strong></a></p>
	</div>
<?php require("footer.php"); ?>